HTTPS Fix attempt #2
moved {rejectUnauthorized: false} from line 34 to line 16 to fix following typescript error: 
/home/travis/build/fuse-box/fuse-box/src/modules/fusebox-websocket/index.ts(34,52): error TS2345: Argument of type '{ rejectUnauthorized: boolean; }' is not assignable to parameter of type 'string | string[]'.
  Object literal may only specify known properties, and 'rejectUnauthorized' does not exist in type 'string | string[]