Fix declarations for noImplicitAny
Omitting the return type of fn causes compile errors in consuming projects that import fuse-box with noImplicitAny compiler option.

node_modules/fuse-box/dist/typings/core/FuseBox.d.ts(63,9): error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/fuse-box/dist/typings/quantum/plugin/ComputerStatementRule.d.ts(8,13): error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/fuse-box/dist/typings/quantum/plugin/ComputerStatementRule.d.ts(14,13): error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/fuse-box/dist/typings/quantum/plugin/QuantumCore.d.ts(30,13): error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.